

###
POST http://localhost:8080/articles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjIwODg4MDU0LCJleHAiOjE2MjA4ODk4NTR9.gKiabkfYugF6l81JZndbgbFVMgXLrd1jTrnxe52QSDukyE7zkK22Gwbla8cfoNCGYH8ngOVYWDvhE-syANQXAQ

{
  "title": "제목",
  "content": "내용",
  "latitude": 0,
  "longitude": 0
}

###
GET http://localhost:8080/articles/1
Content-Type: application/json

###
