

###
POST http://localhost:8080/articles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjIwODkyNzE5LCJleHAiOjE2MjA4OTQ1MTl9.xQozBghivWmstc6SV4wHkmetsEHf0UloN6ZPaQTlvwTz8jrIwtHHXxuO3K0BjNqoRcJpPGMsNtGDM9bP0u-LXQ

{
  "title": "제목",
  "content": "내용",
  "latitude": 0,
  "longitude": 0
}

###
GET http://localhost:8080/articles/1
Content-Type: application/json

###
