POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "nickName" : "하이하이",
  "email" : "dsadsadas@naver.com",
  "password": "dfsfasdsafds"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email" : "dsadsadas@naver.com",
  "password": "dfsfasdsafds"
}

###
