### 전체지도 글에 댓글 작성
POST http://localhost:8080/api/articles/public/1/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjIyNDYyNTU2LCJleHAiOjE2MjI0NjQzN

{
  "content" : "댓글 내용이다 ㅋㅋㅋㅋㅋㅋㅋ"
}

### 개인지도 글에 댓글 작성
POST http://localhost:8080/api/articles/private/1/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjIyNDYyNTU2LCJleHAiOjE2MjI0NjQzN

{
  "content" : "댓글 내용이다 ㅋㅋㅋㅋㅋㅋㅋ"
}

### 그룹지도 글에 댓글 작성
POST http://localhost:8080/api/articles/grouped/1/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjIyNDYyNTU2LCJleHAiOjE2MjI0NjQzN

{
  "content" : "댓글 내용이다 ㅋㅋㅋㅋㅋㅋㅋ"
}
