### 전체지도 글에 댓글 작성
POST http://localhost:8080/articles/public/1/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjIyNDYyNTU2LCJleHAiOjE2MjI0NjQzN

{
  "content" : "댓글 내용이다 ㅋㅋㅋㅋㅋㅋㅋ"
}

### 개인지도 글에 댓글 작성
POST http://localhost:8080/articles/private/1/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjIyNDYyNTU2LCJleHAiOjE2MjI0NjQzN

{
  "content" : "댓글 내용이다 ㅋㅋㅋㅋㅋㅋㅋ"
}

### 그룹지도 글에 댓글 작성
POST http://localhost:8080/articles/grouped/1/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjIyNDYyNTU2LCJleHAiOjE2MjI0NjQzN

{
  "content" : "댓글 내용이다 ㅋㅋㅋㅋㅋㅋㅋ"
}

### 전체지도 글의 댓글목록 조회
GET http://localhost:8080/articles/public/1/comments
Content-Type: application/json

### 개인지도 글의 댓글목록 조회
GET http://localhost:8080/articles/private/1/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjI2ODczNjA0LCJleHAiOjE2MjY4NzU0M

### 그룹지도 글의 댓글목록 조회
GET http://localhost:8080/articles/grouped/1/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjI2ODczNjA0LCJleHAiOjE2MjY4NzU0M
