###
GET http://localhost:8080/users/me/image
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjI1NDc1NTA1LCJleHAiOjE2MjU0NzczMDV9.Dyv7gMRBKI3w2SjUyQoZmzuq0KkMM_IFhiAAia3NfShMBbc9Nt0dYVVw92CeLNpmZqxTwDFgjx5b1hrBfFCvFQ

###
GET http://localhost:8080/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjI1NDc1NTA1LCJleHAiOjE2MjU0NzczMDV9.Dyv7gMRBKI3w2SjUyQoZmzuq0KkMM_IFhiAAia3NfShMBbc9Nt0dYVVw92CeLNpmZqxTwDFgjx5b1hrBfFCvFQ
